/* GERADO por build-audio.mjs — não edite à mão.
   79 falas · vozes Samantha (en) e Luciana (pt).
   Para trocar por gravação humana: regrave o arquivo, mantenha o nome. */
window.CLIPS = {
  "pt:Veterinário.": "audio/pt-veterinario.m4a",
  "en:Vet": "audio/en-vet.m4a",
  "pt:Parabéns! Você é um Pequeno Veterinário!": "audio/pt-parabens-voce-e-um-pequeno-veterinario.m4a",
  "pt:Hora de trabalhar!": "audio/pt-hora-de-trabalhar.m4a",
  "en:dog": "audio/en-dog.m4a",
  "pt:cachorro": "audio/pt-cachorro.m4a",
  "en:cat": "audio/en-cat.m4a",
  "pt:gato": "audio/pt-gato.m4a",
  "en:sick": "audio/en-sick.m4a",
  "pt:doente": "audio/pt-doente.m4a",
  "en:bandage": "audio/en-bandage.m4a",
  "pt:curativo": "audio/pt-curativo.m4a",
  "en:medicine": "audio/en-medicine.m4a",
  "pt:remédio": "audio/pt-remedio.m4a",
  "pt:Um cachorro chegou. Ele está machucado.": "audio/pt-um-cachorro-chegou-ele-esta-machucado.m4a",
  "en:Get the bandage.": "audio/en-get-the-bandage.m4a",
  "en:Here is the bandage. Thank you!": "audio/en-here-is-the-bandage-thank-you.m4a",
  "pt:O curativo está no lugar. Agora ele precisa de remédio.": "audio/pt-o-curativo-esta-no-lugar-agora-ele-precisa-d.m4a",
  "en:Give the medicine.": "audio/en-give-the-medicine.m4a",
  "en:Good job! The medicine helps him.": "audio/en-good-job-the-medicine-helps-him.m4a",
  "pt:Um gato está esperando na porta.": "audio/pt-um-gato-esta-esperando-na-porta.m4a",
  "en:Bring the cat inside.": "audio/en-bring-the-cat-inside.m4a",
  "en:The cat is safe. You are a great vet!": "audio/en-the-cat-is-safe-you-are-a-great-vet.m4a",
  "pt:Bombeiro.": "audio/pt-bombeiro.m4a",
  "en:Firefighter": "audio/en-firefighter.m4a",
  "pt:Parabéns! Você é um Pequeno Bombeiro!": "audio/pt-parabens-voce-e-um-pequeno-bombeiro.m4a",
  "en:fire": "audio/en-fire.m4a",
  "pt:fogo": "audio/pt-fogo.m4a",
  "en:water": "audio/en-water.m4a",
  "pt:água": "audio/pt-agua.m4a",
  "en:ladder": "audio/en-ladder.m4a",
  "pt:escada": "audio/pt-escada.m4a",
  "en:helmet": "audio/en-helmet.m4a",
  "pt:capacete": "audio/pt-capacete.m4a",
  "en:truck": "audio/en-truck.m4a",
  "pt:caminhão": "audio/pt-caminhao.m4a",
  "pt:O alarme tocou! Antes de sair, você precisa se proteger.": "audio/pt-o-alarme-tocou-antes-de-sair-voce-precisa-se.m4a",
  "en:Put on the helmet.": "audio/en-put-on-the-helmet.m4a",
  "en:The helmet is on. Let's go!": "audio/en-the-helmet-is-on-let-s-go.m4a",
  "pt:A janela é lá em cima. Como você chega até ela?": "audio/pt-a-janela-e-la-em-cima-como-voce-chega-ate-el.m4a",
  "en:Climb the ladder.": "audio/en-climb-the-ladder.m4a",
  "en:Up the ladder! Almost there.": "audio/en-up-the-ladder-almost-there.m4a",
  "pt:O fogo ainda está queimando na janela.": "audio/pt-o-fogo-ainda-esta-queimando-na-janela.m4a",
  "en:Put water on the fire.": "audio/en-put-water-on-the-fire.m4a",
  "en:The fire is out. Everyone is safe!": "audio/en-the-fire-is-out-everyone-is-safe.m4a",
  "pt:Chef de Cozinha.": "audio/pt-chef-de-cozinha.m4a",
  "en:Chef": "audio/en-chef.m4a",
  "pt:Parabéns! Você é um Pequeno Chef!": "audio/pt-parabens-voce-e-um-pequeno-chef.m4a",
  "en:egg": "audio/en-egg.m4a",
  "pt:ovo": "audio/pt-ovo.m4a",
  "en:milk": "audio/en-milk.m4a",
  "pt:leite": "audio/pt-leite.m4a",
  "en:pan": "audio/en-pan.m4a",
  "pt:panela": "audio/pt-panela.m4a",
  "en:cake": "audio/en-cake.m4a",
  "pt:bolo": "audio/pt-bolo.m4a",
  "en:hot": "audio/en-hot.m4a",
  "pt:quente": "audio/pt-quente.m4a",
  "pt:Chegou um pedido na cozinha: um bolo de aniversário!": "audio/pt-chegou-um-pedido-na-cozinha-um-bolo-de-anive.m4a",
  "en:Crack the egg.": "audio/en-crack-the-egg.m4a",
  "en:One egg, cracked. Nice work!": "audio/en-one-egg-cracked-nice-work.m4a",
  "pt:O ovo está pronto. Para onde ele vai agora?": "audio/pt-o-ovo-esta-pronto-para-onde-ele-vai-agora.m4a",
  "en:Put it in the pan.": "audio/en-put-it-in-the-pan.m4a",
  "en:Into the pan it goes. Careful, it is hot!": "audio/en-into-the-pan-it-goes-careful-it-is-hot.m4a",
  "pt:Ding! Ficou pronto e o cliente está esperando.": "audio/pt-ding-ficou-pronto-e-o-cliente-esta-esperando.m4a",
  "en:Serve the cake.": "audio/en-serve-the-cake.m4a",
  "en:The cake is perfect. Thank you, chef!": "audio/en-the-cake-is-perfect-thank-you-chef.m4a",
  "pt:Qual trabalho você quer fazer hoje?": "audio/pt-qual-trabalho-voce-quer-fazer-hoje.m4a",
  "pt:Vamos conhecer as palavras.": "audio/pt-vamos-conhecer-as-palavras.m4a",
  "pt:Agora, ouça e toque.": "audio/pt-agora-ouca-e-toque.m4a",
  "pt:Toque em": "audio/pt-toque-em.m4a",
  "pt:Quase!": "audio/pt-quase.m4a",
  "pt:Quase! Tenta outra vez.": "audio/pt-quase-tenta-outra-vez.m4a",
  "pt:Testando um, dois, três.": "audio/pt-testando-um-dois-tres.m4a",
  "pt:Isso!": "audio/pt-isso.m4a",
  "pt:Muito bem!": "audio/pt-muito-bem.m4a",
  "pt:Perfeito!": "audio/pt-perfeito.m4a",
  "pt:Boa!": "audio/pt-boa.m4a",
  "pt:É isso aí!": "audio/pt-e-isso-ai.m4a"
};
